### ISSUE TITLE
Pytorch

### ISSUE THREAD

**Issue by MaAl13** [skoohy/GPT-PINN#1]
Hello,

i wanted to ask what the reason was that you combine Tensorflow and Pytorch. Would it have been possible to write the whole code in PyTorch only?

**Comment by skoohy** [comment]
> Hello,
> 
> i wanted to ask what the reason was that you combine Tensorflow and Pytorch. Would it have been possible to write the whole code in PyTorch only?

Hi,

Yes, it is possible to write the code in PyTorch only, that is what we did for the Klein-Gordon and Burgers' equation, only the Allen-Cahn equation uses both PyTorch and TensorFlow. We did this because we ran into issues training the full/vanilla PINN on the Allen-Cahn equation which is documented in various PINN papers. We ran into the SA-PINN paper (https://arxiv.org/abs/2009.04544) which builds an adaptive PINN to solve the Allen-Cahn equation. The SA-PINN was written in TensorFlow and the GPT-PINN code began in PyTorch. Instead of rewriting the entire SA-PINN code in PyTorch, we combined the two models so they could work in unison. 

Hope this answers your question.
